/**
 * Warehouse API
 * API endpoints for a warehouse services documented on swagger
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jorge.sindelar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Product details included in a shipment.
 */
export interface ShipmentProduct { 
    /**
     * Unique identifier for the product.
     */
    productId: number;
    /**
     * Quantity of the product in the shipment.
     */
    quantity: number;
}

