/**
 * Warehouse API
 * API endpoints for a warehouse services documented on swagger
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jorge.sindelar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipmentProduct } from './shipmentProduct';


/**
 * Schema of shipment.
 */
export interface Shipment { 
    /**
     * Unique identifier for the shipment.
     */
    id: number;
    /**
     * Name of the company associated with the shipment.
     */
    companyName: string;
    /**
     * Unique identifier for the shipment.
     */
    shipmentId?: string;
    /**
     * Date when the shipment supposed to be send.
     */
    shipmentDate: string;
    /**
     * Identifier for the current status of the shipment.
     */
    statusId: number;
    /**
     * Date when the shipment was created.
     */
    createdAt?: string;
    /**
     * Date when the shipment was last updated.
     */
    updatedAt?: string;
    /**
     * List of products included in the shipment.
     */
    products: Array<ShipmentProduct>;
}

