/**
 * Warehouse API
 * API endpoints for a warehouse services documented on swagger
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jorge.sindelar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationErrorErrorsInner } from './validationErrorErrorsInner';


/**
 * An object representing a validation error from AJV.
 */
export interface ValidationError { 
    /**
     * An array of errors that occurred during validation.
     */
    errors: Array<ValidationErrorErrorsInner>;
}

